version: "3"
services:
  golang-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    stdin_open: true
    volumes: 
      - ./:/usr/src
    ports: 
      - 8000:8080
    depends_on:
      - golang-db
  golang-db:
    image: mysql:8.0
    container_name: db
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass